### ISSUE TITLE
Add cffi as dependency in pip

### ISSUE THREAD

**Issue by adrian-vlad** [irvinren/shared_atomic#2]
Hi,
if `cffi` is needed for this library, then it would be best to add it as a dependency in pip.

I try to install this library using `pip install cffi shared_atomic` but it returns an error when running the setup for shared_atomic. If I do `pip install cffi` and then `pip install shared_atomic`, everything works fine, but I prefer them to be installed in one go because it makes things easier in ansible.

Would you be able to make this change?
Thanks,
Adrian

**Comment by irvinren** [comment]
Please wait , doing it.

**Comment by irvinren** [comment]
Finished, 2.1.5 and 2.1.6 are all good in setuptools

**Comment by adrian-vlad** [comment]
The dependency works, but there is another issue now:
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import shared_atomic
  File "/home/X/.local/lib/python3.8/site-packages/shared_atomic/__init__.py", line 712, in <module>
    from shared_atomic.atomic_bytearray import atomic_bytearray
  File "/home/X/.local/lib/python3.8/site-packages/shared_atomic/atomic_bytearray.py", line 5, in <module>
    import shared_atomic_.lib
ModuleNotFoundError: No module named 'shared_atomic_'
```
I'm working on Ubuntu/Debian.

Can you have a look at that?
Thank you

**Comment by irvinren** [comment]
Dear customer,

I am using Ubuntu/Debian do test, it is fine. What version are you using?
xiquanren@ubuntu:~/.local/lib/python3.6/site-packages$ pip3 install shared_atomic==2.1.6
Collecting shared_atomic==2.1.6
Collecting cffi>=1.0 (from shared_atomic==2.1.6)
  Using cached https://files.pythonhosted.org/packages/49/7b/449daf9cacfd7355cea1b4106d2be614315c29ac16567e01756167f6daab/cffi-1.15.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.0->shared_atomic==2.1.6)
  Using cached https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl
Installing collected packages: pycparser, cffi, shared-atomic
Successfully installed cffi-1.15.0 pycparser-2.21 shared-atomic-2.1.6

**Comment by irvinren** [comment]
xiquanren@ubuntu:~/.local/lib/python3.6/site-packages$ python3
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shared_atomic

**Comment by adrian-vlad** [comment]
There was no `shared_atomic_.abi3.so` in that directory.

I tried on a clean machine and it worked correctly. I did some investigation and it may have been an issue with the cache. I ran `python3.8 -m pip install --no-cache-dir shared_atomic==2.1.6` and it installed fine. So it was probably a quirk of pip.

Either way, thanks for your help. Everything is fine now.
